sudo: false
language: python
python:
- '2.6'
- '2.7'
- '3.5'
- '3.6'
install:
- pip install requests
- pip install nose
- pip install pep8
- pip install dicttoxml
script:
- pep8 --max-line-length=180 qcloud_cos/.
- nosetests -s -v ut/
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: dt3310321
  password:
    secure: LoSq2wZPbXJ4DkYCQk6Oi0mI6iwhAiE6Xgyvl+Rv1geYqPTuI8ht7dps2ENHM2gj8JqhsZ7C5p/g9P6YuIBk0OTYKewHgHBnUAQwePzu0N1ofzJtJVoSbhW0aPeNfF6DxkTPscBGCHuMyHb/r/buHa3hLoJKxF0l50jEUugTJnP6Ms7a3oa7GaLIJ4QAKMZtLTN31iIcW40r2vVwH+J3JyCr/xeUhwT5/MlaN9c5lLjh7eUig2DA8/6DpqPOm+wV+cn6dh2w2I294cSRsUPJJla63g0YTYbPT9RKeC2D5GiyfqCYAEYzvKdlBJ5hCURh5rxrjOCGlde4Inq0uX6AMETOnvJhkvDMQ5cZ2sUKUy4BC021xvVBdQ44MFI5oGAGUIHbhsAs6wKwWo2ZvmJ5A2Oh0Ny6cx+PzGkZVN9afDUeiGQQcXvHFPw/oZrtQo/H8y8YsIQedBbHOY4RUnt/ID2xOOaZ50REIaGPZJq4hXGgggRh14bKcFcAH/DkiMiBi0bMRhxUOUI57T+4F5Jl5AdrZg/j3FjVn4Jv3Xcr/+N6Xp2QIttRkpa3XpE7N3378V7PKMlGQs0YFWGqDKR9hffMgDQ6qC+E7/OylmxIrOHv4545QCfVUuOhkq9v6IINc1XkKZ4r0GpNk33yr08lZ+jlsMKZvycBF5W2Yp8LWkM=
  on:
    tags: true
    branch: master
env:
  global:
    secure: EZkLI0XwvSQD3Z4z62LBh5TojjwTlRRenN8p8KIvRnh40tSM5mZLV3N4tBFviPu4EcdVhlELgUrbk0y4kLePRnIIVCokcw1wWR1e1qWsa0bHO7vhlxA8yzmhUl8Zi+WiYmKJIKxadmSTS30ycRZqxtn8RC1geSIvUefxmyS4ei6X5gsQn6vT+KU5/ONSQZ0BU4PoDGss7s1lNGWRv6c1F3N3yemxtzA6Lf0ASqm/ZlTqx6IuSRxnrNW1m3V2JedW60iheOyXJIA719IUZuKmczOxqjBwDf7IxgkuEFCbSJMRAoH50KxPX5ZhlBfbiuUQtm2sdrLo5bHjeACGM1m/lZtT+DrjwC/q0iBnSL7IQPGWK54UdvnH6bycGkHovcU4HjJKxg0dK9jHhShv9GoBHrpvYVvr+KlSHCGldtNugGZR3TnWjsFY6vfbILV6Qy49CAHjjt27SVwx5tNZhauuUrlJAtMsZ5J7olusLtxOz5neAilwnb+PPpJMWjPyBAT/DqRrl9D8hQ4xuBL/vbX28EZO4zW9Z3uGnExlhQaAFTosbxkzCaqr0QatVJIlkDb70BB6UrAVY+6uEusTrleCHTEyzbhiKZgoKSJMNUUfZ3rwH2NqUn7DWgJt4CvrXG+P5HIouZOJ1IMtCtCGtS6vfwOHAhP8yXYXpbXY/ZQwXY0=
